import type {Metadata} from "next";
import { Providers } from "@/components/Providers"
import {Bodoni_Moda, Geist, Geist_Mono, Hanken_Grotesk} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import React from "react";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const bodoniModa = Bodoni_Moda({
    variable: "--font-display-sans",
    subsets: ["latin"],
    weight: ["400", "500", "600"],
});

const hankenGrotesk = Hanken_Grotesk({
    variable: "--font-sans-body",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Verdant Luxe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased",
                geistSans.variable, geistMono.variable,
                "font-sans", geist.variable)}
        >
            <body className={`${bodoniModa.variable} ${hankenGrotesk.variable} 
            min-h-screen bg-background font-sans text-on-surface 
            antialiased overflow-x-hidden`}>
                <main>
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    );
}
